# Generated by Django 3.2.6 on 2021-10-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Others'), ('Not specified', 'Do not wish to specify')], default='Female', max_length=15)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('pro_pic', models.ImageField(default='/profile_photos/default_pic.jpg', upload_to='profile_photos/')),
                ('acc_creation_date', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
