# Generated by Django 3.2.6 on 2021-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('birthdate', models.DateTimeField(blank=True)),
                ('mobile_no', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
