# Generated by Django 3.2.6 on 2021-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.IntegerField(unique=True),
        ),
    ]
