# Generated by Django 3.2.6 on 2021-10-12 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='acc_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 10, 41, 239481)),
        ),
    ]
