# Generated by Django 3.2.6 on 2021-10-12 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_users_acc_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='acc_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
