# Generated by Django 3.2.6 on 2021-11-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_authenticatedd',
            field=models.BooleanField(default=False),
        ),
    ]
